# Generated by Django 3.0.7 on 2020-06-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiview',
            name='stu_id',
        ),
        migrations.AddField(
            model_name='apiview',
            name='stu_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apiview',
            name='stu_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apiview',
            name='stu_gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apiview',
            name='stu_location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
